### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by stremsin** [rhiestan/EncFSMP#1]
Hi,

Is it possible to compile EncFSMP as a portable package, so it can run on any machine without being installed?

**Comment by rhiestan** [comment]
The executable EncFSMP (as is in the installer package) can be run without installation. However, it does not allow to mount a encfs folder, only to export one. To mount an encfs folder, EncFSMP requires an installed PFM driver.
See FAQ: [https://encfsmp.sourceforge.io/faq.html](https://encfsmp.sourceforge.io/faq.html) , last item.
