### ISSUE TITLE
Upgrading EncFS

### ISSUE THREAD

**Issue by AdrianVerde** [rhiestan/EncFSMP#10]
Hello, do you plan on upgrading EncFS to any of the newer versions released by vgough on https://github.com/vgough/encfs?

**Comment by rhiestan** [comment]
Yes I do, but the lack of free time on my part makes it very difficult to work on it.

**Comment by rhiestan** [comment]
EncFSMP 0.99.0 is now using encfs 1.9.5, the most recent version.
