### ISSUE TITLE
Another instance of Encfs MP is already running (windows 10)

### ISSUE THREAD

**Issue by bavure** [rhiestan/EncFSMP#19]
On windows 10, my Encfs MP has crashed. when I want to restart it I get "Another instance of Encfs MP3 is already running, what can I do to solve this (I guess there is a temporary file to remove or something like this).
Thanks in advance for your help.

**Comment by rhiestan** [comment]
EncFSMP uses the wxWidgets class wxSingleInstanceChecker. On Windows, it creates a Mutex. While EncFSMP is running, you might be able to delete the mutex with Process Explorer (sysinternals.com). Unfortunately, I don't know how to delete a mutex created by a dead process.

**Comment by bavure** [comment]
Thanks a lot for your answer.
Have a good day.
La Bavure


Le sam. 10 oct. 2020 à 18:06, Roman Hiestand <notifications@github.com> a
écrit :
