### ISSUE TITLE
macos Another instance if EncfsMP is already running.

### ISSUE THREAD

**Issue by mnatalini** [rhiestan/EncFSMP#3]
Occasionally we get this message on macos -> http://prnt.sc/eqmtee

macOS 10.12.3
EncFS MP x64 0.10.6

Can't really reproduce the issue and what a causes it. Usually 2 -3 restarts helps and shutting down all other apps running.

**Comment by rhiestan** [comment]
EncFSMP uses the class wxSingleInstanceChecker to check that only one instance is running at a time. I don't know exactly what it does on Mac OS, apparently it creates and locks a certain file.
Maybe deleting this file would help. Unfortunately I don't know where this file is created, and the name changes probably.
Do you always exit EncFSMP cleanly, or does it crash sometimes? How does this situation occur?

**Comment by mnatalini** [comment]
Apparently it gets fixed after deleting in user profiles the temp file encfsmp-"profilename".
