### ISSUE TITLE
More control about the MountPoints?

### ISSUE THREAD

**Issue by cyberpunkbln** [rhiestan/EncFSMP#9]
Hello,

is it possible to became more control about the mountpoints? That i can choose in which folder encfmp mount  the encfs-volume outside c:\Volumes?

thx

**Comment by rhiestan** [comment]
No, sorry, this is not possible. PFM (the underlying file system component) only allows mount points to be inside C:\Volumes. Of course you can always create a mount point with a drive letter, or hard links to C:\Volumes\mount_point.
